apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-nginx
spec:
  params:
  - name: IMAGE
    type: string

  workspaces:
  - name: source

  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:latest
    script: |
      /kaniko/executor \
        --dockerfile=$(workspaces.source.path)/Dockerfile \
        --context=$(workspaces.source.path) \
        --destination=$(params.IMAGE)
